//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : lpp
	/// Data Source    : lpp21744.cfyerfwcpdul.eu-central-1.rds.amazonaws.com
	/// Server Version : 9.5.4
	/// </summary>
	public partial class lppDB : LinqToDB.Data.DataConnection
	{
		public ITable<degree>  degrees  { get { return this.GetTable<degree>(); } }
		public ITable<student> students { get { return this.GetTable<student>(); } }

		public lppDB()
		{
			InitDataContext();
		}

		public lppDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table(Schema="public", Name="degrees")]
	public partial class degree
	{
		[PrimaryKey, Identity] public long   id   { get; set; } // bigint
		[Column,     NotNull ] public string name { get; set; } // character varying(50)
		[Column,     NotNull ] public string code { get; set; } // character varying(6)

		#region Associations

		/// <summary>
		/// FK_degree_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="degree_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<student> degrees { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="students")]
	public partial class student
	{
		[PrimaryKey, Identity   ] public long   id                { get; set; } // bigint
		[Column,     NotNull    ] public string name              { get; set; } // character varying
		[Column,     NotNull    ] public string surname           { get; set; } // character varying
		[Column,        Nullable] public string govern_identifier { get; set; } // character varying
		[Column,        Nullable] public long?  degree_id         { get; set; } // bigint

		#region Associations

		/// <summary>
		/// FK_degree
		/// </summary>
		[Association(ThisKey="degree_id", OtherKey="id", CanBeNull=true, KeyName="FK_degree", BackReferenceName="degrees")]
		public degree degree { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static degree Find(this ITable<degree> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static student Find(this ITable<student> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
